sudo: false
language: java
jdk:
  - openjdk8
  - openjdk11
cache:
  directories:
  - $HOME/.m2
install:
  - echo 'skipped'
script:
  - travis_retry ./mvnw test-compile
  - travis_retry ./mvnw '-Dtest=test_locally.**.*Test' test -DfailIfNoTests=false
  - travis_retry ./mvnw install -Dmaven.test.skip=true
  - travis_retry ./mvnw duplicate-finder:check
