sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10 # just because oracle jdk does not work
  - oraclejdk11
  - openjdk11
cache:
  directories:
  - $HOME/.m2
install: echo 'skipped'
script: ./mvnw test-compile && ./mvnw '-Dtest=test_locally.**.*Test' test -DfailIfNoTests=false
