sudo: false
language: java
cache:
  directories:
    - $HOME/.m2
install:
  - echo $JAVA_HOME
  - echo 'skipped'
matrix:
  # LTS version
  - jdk: openjdk8
    env:
      - CODECOV="true"
    script: travis_retry ./scripts/run_no_prep_tests.sh
  # LTS version
  - jdk: openjdk11
    env:
      - CODECOV="false"
      - MAVEN_OPTS=-Djdk.tls.client.protocols=TLSv1.2
    script: travis_retry ./scripts/run_no_prep_tests.sh
  # non-LTS but latest
  - jdk: openjdk14
    env:
      - CODECOV="false"
    script: travis_retry ./scripts/run_no_prep_tests.sh
  # To detect duplicated classes
  - jdk: openjdk11
    env:
      - CODECOV="false"
    script:
      - travis_retry ./mvnw install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true --no-transfer-progress
      - travis_retry ./mvnw duplicate-finder:check --no-transfer-progress
after_success:
  - test "$CODECOV" = "true" && bash <(curl -s https://codecov.io/bash)
